# Generated by Django 4.0 on 2021-12-18 02:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('csvName', models.CharField(max_length=1000)),
                ('givenUrl', models.CharField(default='#', max_length=1000)),
                ('csvUrl', models.CharField(max_length=1000)),
                ('csvRows', models.IntegerField(default=0)),
                ('csvData', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('folder', models.CharField(max_length=1000)),
                ('Url', models.CharField(max_length=1000)),
                ('imgLinks', models.TextField()),
                ('numImg', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('publicID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.csv')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.images')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=1000, null=True)),
                ('cname', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='configTemplate',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('bName', models.CharField(blank=True, max_length=1024)),
                ('bLogo', models.TextField(blank=True)),
                ('bHead', models.CharField(blank=True, max_length=1024)),
                ('bDesc', models.TextField(blank=True)),
                ('bLocation', models.TextField(blank=True)),
                ('bSite', models.TextField(blank=True)),
                ('bCTA', models.CharField(blank=True, max_length=1024)),
                ('bMail', models.CharField(blank=True, max_length=1024)),
                ('bPhone', models.CharField(blank=True, max_length=16)),
                ('rawjson', models.JSONField(blank=True, null=True)),
                ('renderedjson', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.template')),
            ],
        ),
    ]
