pre = {'Customer1': 'jhaatu',
       'Customer2': 'tony',
       'Customer3': 'Vladmir',
       'Location1': 'India',
       'Location2': 'NYC',
       'Location3': 'Russia',
       'csrfmiddlewaretoken': 'evPzpwgKccanBNMQEvjAZVSnN4EKsCZdgoyMuxidZV9iFgpNoXCPCMZ17blfCBib',
       'faqBlockDescription': 'Some question and their answer',
       'faqBlockTitle': 'Some question',
       'faqCustomerName1': 'a1',
       'faqCustomerName2': 'a2',
       'faqCustomerName3': 'a3',
       'faqDescription1': 'c1',
       'faqDescription2': 'c2',
       'faqDescription3': 'c3',
       'faqTitle1': 'questions1',
       'faqTitle2': 'q2',
       'faqTitle3': 'q1',
       'faqnum': '3',
       'id': 'd814d51e-3366-4401-ba3c-abb29fe77d57',
       'indexDesc': 'Our desc ',
       'indexTitle': 'This contains the job ',
       'interlink01Title': 'the jobs',
       'interlink02Title': 'managerial jobs',
       'interlink03Title': 'us jobs',
       'interlink04Title': 'texas city jobs',
       'interlink05Title': 'canadian jobs',
       'interlink06Title': 'salary at delhi',
       'interlinkTestimonial': 'True users says',
       'packageBlockDescription': 'package description',
       'packageBlockTitle': 'some package',
       'peoplenum': '3',
       'productBlockDescription': 'Manager Jobs in Delhi',
       'productBlockTitle': 'Manager Jobs in Delhi',
       'productBreadcrumb': 'salary at delhi',
       'productButtonCta': 'tel:9078101920',
       'productButtonRedirect': 'lets check more',
       'productDescription': '$description',
       'productLabel': '$type',
       'productName': '$salary=$city{delhi}',
       'productSlug': 'salary-delhi',
       'productTitle': 'salary at delhi',
       'solnum': '3',
       'solutionBlockDescription': 'Discuss Solutions description',
       'solutionBlockTitle': 'Discuss Solutions',
       'solutiondescription1': 'c1',
       'solutiondescription2': 'c2',
       'solutiondescription3': 'c3',
       'solutionlabel1': 'd1',
       'solutionlabel2': 'd2',
       'solutionlabel3': 'd3',
       'solutiontitle1': 's1',
       'solutiontitle2': 's2',
       'solutiontitle3': 's3',
       'topic01BlockDescription': 'We gonna be listing jobs',
       'topic01BlockTitle': 'Jobs',
       'topic01Breadcrumb': 'get jobs',
       'topic01Description': '$description',
       'topic01Label': '$salary= Salary starts from::before',
       'topic01Name': '$type',
       'topic01Slug': 'jobs',
       'topic01Title': 'jobs in all over world',
       'topic02BlockDescription': 'List of manager job that u can get',
       'topic02BlockTitle': 'Manager Jobs',
       'topic02Breadcrumb': 'manager jobs',
       'topic02Description': '$description',
       'topic02Label': '$city=jobs in::before',
       'topic02Name': '$type=$type{manager}',
       'topic02Slug': 'manager-job',
       'topic02Title': 'Manager job',
       'topic03BlockDescription': 'get to know about Manager Jobs in US',
       'topic03BlockTitle': 'Manager Jobs in US',
       'topic03Breadcrumb': 'jobs in usa',
       'topic03Description': '$description',
       'topic03Label': '$salary',
       'topic03Name': '$type=$type{manager};$country{USA}',
       'topic03Slug': 'Manager-Jobs-in-US',
       'topic03Title': 'Manager Jobs in US',
       'topic04BlockDescription': 'some great Manager Jobs in texas',
       'topic04BlockTitle': 'Manager Jobs in texas',
       'topic04Breadcrumb': 'Manager Jobs in texas',
       'topic04Description': '$description',
       'topic04Label': '$salary',
       'topic04Name': '$type=$type{manager};$city{ontario}',
       'topic04Slug': 'Manager-Jobs-in-texas',
       'topic04Title': 'Manager Jobs in texas',
       'topic05BlockDescription': 'Manager Jobs in Dallas County',
       'topic05BlockTitle': 'Manager Jobs in Dallas County',
       'topic05Breadcrumb': 'Manager Jobs in Dallas County',
       'topic05Description': '$description',
       'topic05Label': '$salary',
       'topic05Name': '$type=$type{manager};$country{Turkey}',
       'topic05Slug': 'Manager Jobs in Dallas County',
       'topic05Title': 'Manager Jobs in Dallas County',
       'value01Title': 'tasty',
       'value02Title': 'healthy',
       'value03Title': 'worthy',
       'value04Title': 'fast delivery',
       'valueDesc': 'Bahut sahi desc',
       'valueTitle': 'Bahut sahi'}
